format = """
$username$hostname$directory$git_branch$git_commit$git_state$git_status$package$jobs
$character"""

# Inserts a blank line between shell prompts
add_newline = true

[character]
success_symbol = "[ »](bold green)"
error_symbol = "[ »](bold red)"
vicmd_symbol = "[V:](bold italic fg:blue)"

[directory]
style = "bold purple"

[git_branch]
style = "yellow"
symbol = " "

[git_commit]
style = "yellow"

[git_status]
format = '([$all_status$ahead_behind]($style) )'
style = "yellow"
ahead = '[↑ ](blue)'
behind = '[↓ ](blue)'
conflicted = '[⚠ ](#f70067)'
diverged = '[↕ ](#f70067)'

deleted = '[✗ ](bright-red)'
modified = '[⊕ ](bright-red)'
renamed = '[⟷ ](bright-red)'
staged = '[⊕ ](green)'
stashed = '[◫ ](white)'
untracked = '[? ](bright-yellow)'

[hostname]
style = "bold blue"
format = '[$hostname]($style)[| ](bold dimmed blue)'

[jobs]
symbol = "✶"
style = "cyan"

[username]
style_root = "bold red"
style_user = "bold blue"
format = '[$user]($style)[@](bold dimmed blue)'
